# Generated by Django 5.0.7 on 2025-11-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='full_name',
            field=models.CharField(default='Unknown Buyer', max_length=255),
            preserve_default=False,
        ),
    ]
